import enum


class CloudRegion(enum.Enum):
    AWS_AP_NORTHEAST_1 = 'AWS_AP_NORTHEAST_1'
    AWS_AP_NORTHEAST_2 = 'AWS_AP_NORTHEAST_2'
    AWS_AP_SOUTHEAST_1 = 'AWS_AP_SOUTHEAST_1'
    AWS_AP_SOUTHEAST_2 = 'AWS_AP_SOUTHEAST_2'
    AWS_AP_SOUTH_1 = 'AWS_AP_SOUTH_1'
    AWS_EU_CENTRAL_1 = 'AWS_EU_CENTRAL_1'
    AWS_EU_WEST_1 = 'AWS_EU_WEST_1'
    AWS_SA_EAST_1 = 'AWS_SA_EAST_1'
    AWS_US_EAST_1 = 'AWS_US_EAST_1'
    AWS_US_WEST_1 = 'AWS_US_WEST_1'
    AWS_US_WEST_2 = 'AWS_US_WEST_2'
    GOOGLE_ASIA_EAST_1 = 'GOOGLE_ASIA_EAST_1'
    GOOGLE_EUROPE_WEST_1 = 'GOOGLE_EUROPE_WEST_1'
    GOOGLE_US_CENTRAL_1 = 'GOOGLE_US_CENTRAL_1'
    GOOGLE_US_EAST_1 = 'GOOGLE_US_EAST_1'
    KUBERNETES = 'KUBERNETES'

    @staticmethod
    def default():
        return CloudRegion.GOOGLE_EUROPE_WEST_1
