import enum


class Font(enum.Enum):
    DEJAVUSANS = 'DEJAVUSANS'
    DEJAVUSERIF = 'DEJAVUSERIF'
    DEJAVUSANSMONO = 'DEJAVUSANSMONO'
    ROBOTOMONO = 'ROBOTOMONO'
    ROBOTOBLACK = 'ROBOTOBLACK'
    ROBOTO = 'ROBOTO'
    ROBOTOCONDENSED = 'ROBOTOCONDENSED'
