from enum import Enum


class StreamMode(Enum):
    PER_TITLE_TEMPLATE = 'PER_TITLE_TEMPLATE'
    STANDARD = 'STANDARD'
    PER_TITLE_RESULT = 'PER_TITLE_RESULT'
    PER_TITLE_TEMPLATE_FIXED_RESOLUTION = 'PER_TITLE_TEMPLATE_FIXED_RESOLUTION'
    PER_TITLE_TEMPLATE_FIXED_RESOLUTION_AND_BITRATE = 'PER_TITLE_TEMPLATE_FIXED_RESOLUTION_AND_BITRATE'
