from .abstract_input import AbstractInput
from .s3_input import S3Input
from .gcs_input import GCSInput
from .azure_input import AzureInput
from .ftp_input import FTPInput
from .sftp_input import SFTPInput
from .http_input import HTTPInput
from .https_input import HTTPSInput
from .aspera_input import AsperaInput
from .rtmp_input import RTMPInput
from .analysis import *
