# coding: utf-8
from enum import Enum


class StreamMode(Enum):
    """
    allowed enum values
    """
    STANDARD = "STANDARD"
    PER_TITLE_TEMPLATE = "PER_TITLE_TEMPLATE"
    PER_TITLE_TEMPLATE_FIXED_RESOLUTION = "PER_TITLE_TEMPLATE_FIXED_RESOLUTION"
    PER_TITLE_TEMPLATE_FIXED_RESOLUTION_AND_BITRATE = "PER_TITLE_TEMPLATE_FIXED_RESOLUTION_AND_BITRATE"
    PER_TITLE_RESULT = "PER_TITLE_RESULT"
